-- Kelimelik A2 answer-pool refresh + recent-answer protection
-- A1 ve D1 değiştirilmez; eski oyun kodları/günlük seri korunur.
-- Yeni tek/online oyunlarda A2 kullanılır ve son cevapların kısa aralıkta tekrarı engellenir.

insert into public.multiplayer_guess_words(length,word) values
(5,'BİNGO'),
(5,'BİYOM'),
(5,'FOTON'),
(6,'MARŞAL')
on conflict (length,word) do nothing;

-- A1'i A2'nin tabanı olarak kopyala.
insert into public.multiplayer_answer_words(answer_version,length,word,enabled)
select 'A2',length,word,enabled
from public.multiplayer_answer_words
where answer_version='A1'
on conflict (answer_version,length,word) do update set enabled=excluded.enabled;

-- Frekans/yaygınlık odaklı kontrollü A2 cevap takviyesi.
insert into public.multiplayer_answer_words(answer_version,length,word,enabled)
select 'A2',v.length,v.word,true
from (values
(4,'ABLA'),
(4,'ACİL'),
(4,'ACİZ'),
(4,'ADAY'),
(4,'ADAŞ'),
(4,'ADİL'),
(4,'AFET'),
(4,'AKIM'),
(4,'AKIN'),
(4,'AKIŞ'),
(4,'AKOR'),
(4,'AKSİ'),
(4,'AKUT'),
(4,'ALAY'),
(4,'ALEM'),
(4,'ALEV'),
(4,'ALGI'),
(4,'ALIM'),
(4,'ALIN'),
(4,'ALIŞ'),
(4,'ALMA'),
(4,'ALÇI'),
(4,'AMAN'),
(4,'AMAÇ'),
(4,'AMEL'),
(4,'AMFİ'),
(4,'AMİN'),
(4,'AMİR'),
(4,'ANNE'),
(4,'ANOT'),
(4,'ARAÇ'),
(4,'ARGO'),
(4,'ARKA'),
(4,'ARMA'),
(4,'ARYA'),
(4,'ARZU'),
(4,'ASAL'),
(4,'ASIR'),
(4,'ASKI'),
(4,'ASLA'),
(4,'ASMA'),
(4,'ASİT'),
(4,'ATEŞ'),
(4,'ATIK'),
(4,'ATIM'),
(4,'ATIŞ'),
(4,'ATOM'),
(4,'AVCI'),
(4,'AVLU'),
(4,'AVRO'),
(4,'AVUÇ'),
(4,'AYAR'),
(4,'AYET'),
(4,'AYIK'),
(4,'AYIN'),
(4,'AYNA'),
(4,'AYNI'),
(4,'AYVA'),
(4,'AZAP'),
(4,'AZAR'),
(4,'AZAT'),
(4,'AZIK'),
(4,'AZOT'),
(4,'AZİM'),
(4,'AZİZ'),
(4,'AÇIK'),
(4,'AĞAÇ'),
(4,'AĞIL'),
(4,'AĞIT'),
(4,'AĞIZ'),
(4,'AĞRI'),
(4,'AŞIK'),
(4,'BACI'),
(4,'BAHT'),
(4,'BALE'),
(4,'BALO'),
(4,'BANT'),
(4,'BARO'),
(4,'BAZI'),
(4,'BENT'),
(4,'BLOK'),
(4,'BLUZ'),
(4,'BLÖF'),
(4,'BOKS'),
(4,'BONO'),
(4,'BORU'),
(4,'BORÇ'),
(4,'BOZA'),
(4,'BROŞ'),
(4,'BRÜT'),
(4,'BUJİ'),
(4,'BURS'),
(4,'BURÇ'),
(4,'BÜRO'),
(4,'BÜST'),
(4,'CADI'),
(4,'CAMİ'),
(4,'CEFA'),
(4,'CELP'),
(4,'CENK'),
(4,'CİLA'),
(4,'CİRO'),
(4,'DAHA'),
(4,'DAHİ'),
(4,'DAMA'),
(4,'DANS'),
(4,'DARP'),
(4,'DART'),
(4,'DAYI'),
(4,'DAİM'),
(4,'DAİR'),
(4,'DEFA'),
(4,'DEHA'),
(4,'DEMO'),
(4,'DENK'),
(4,'DEPO'),
(4,'DERE'),
(4,'DERT'),
(4,'DERZ'),
(4,'DEVA'),
(4,'DEVE'),
(4,'DOKU'),
(4,'DOST'),
(4,'DOĞA'),
(4,'DRAM'),
(4,'DURU'),
(4,'DUYU'),
(4,'DÜZE'),
(4,'DİSK'),
(4,'DİZİ'),
(4,'EBAT'),
(4,'EBRU'),
(4,'ECEL'),
(4,'ECZA'),
(4,'EDAT'),
(4,'EDEP'),
(4,'EFOR'),
(4,'EKOL'),
(4,'EKSİ'),
(4,'EKİN'),
(4,'EKŞİ'),
(4,'ELEK'),
(4,'ELLİ'),
(4,'ELTİ'),
(4,'EMEK'),
(4,'EMEL'),
(4,'EMİN'),
(4,'ENSE'),
(4,'EPİK'),
(4,'ESAS'),
(4,'ESEF'),
(4,'ESEN'),
(4,'ESKİ'),
(4,'ESİR'),
(4,'ETAP'),
(4,'ETEK'),
(4,'ETKİ'),
(4,'ETÜT'),
(4,'ETİK'),
(4,'EVET'),
(4,'EVLİ'),
(4,'EYER'),
(4,'EZAN'),
(4,'EZEL'),
(4,'EZGİ'),
(4,'EZME'),
(4,'EZİK'),
(4,'EĞRİ'),
(4,'EĞİK'),
(4,'EŞEK'),
(4,'EŞYA'),
(4,'EŞİT'),
(4,'FAAL'),
(4,'FAKS'),
(4,'FARK'),
(4,'FARZ'),
(4,'FAUL'),
(4,'FEDA'),
(4,'FELÇ'),
(4,'FERT'),
(4,'FEZA'),
(4,'FLAŞ'),
(4,'FLÜT'),
(4,'FOBİ'),
(4,'FONT'),
(4,'FORM'),
(4,'FOTO'),
(4,'FOYA'),
(4,'FRAK'),
(4,'FREN'),
(4,'FUAR'),
(4,'FÜME'),
(4,'FÜZE'),
(4,'FİDE'),
(4,'FİLO'),
(4,'FİRE'),
(4,'FİİL'),
(4,'GAGA'),
(4,'GALA'),
(4,'GAMA'),
(4,'GASP'),
(4,'GAYE'),
(4,'GAİP'),
(4,'GEBE'),
(4,'GEZİ'),
(4,'GOLF'),
(4,'GRAM'),
(4,'GREV'),
(4,'GRUP'),
(4,'GRİP'),
(4,'GUAŞ'),
(4,'GÜYA'),
(4,'GİBİ'),
(4,'GİŞE'),
(4,'HACI'),
(4,'HADİ'),
(4,'HALA'),
(4,'HALE'),
(4,'HALK'),
(4,'HANE'),
(4,'HANİ'),
(4,'HARF'),
(4,'HARP'),
(4,'HATA'),
(4,'HEBA'),
(4,'HECE'),
(4,'HINÇ'),
(4,'HIRS'),
(4,'HOBİ'),
(4,'HOCA'),
(4,'HUŞU'),
(4,'HİBE'),
(4,'HİLE'),
(4,'HİNT'),
(4,'HİZA'),
(4,'ILIK'),
(4,'IŞIL'),
(4,'IŞIN'),
(4,'JANT'),
(4,'JEST'),
(4,'JUDO'),
(4,'JÖLE'),
(4,'JÜRİ'),
(4,'KAFE'),
(4,'KAJU'),
(4,'KALE'),
(4,'KALP'),
(4,'KAMP'),
(4,'KAMU'),
(4,'KANO'),
(4,'KAOS'),
(4,'KARE'),
(4,'KARO'),
(4,'KASK'),
(4,'KAST'),
(4,'KAZA'),
(4,'KAŞE'),
(4,'KENE'),
(4,'KERE'),
(4,'KESE'),
(4,'KEZA'),
(4,'KINA'),
(4,'KIRK'),
(4,'KITA'),
(4,'KIYI'),
(4,'KLAN'),
(4,'KLON'),
(4,'KLOR'),
(4,'KLİP'),
(4,'KOCA'),
(4,'KOKU'),
(4,'KOLİ'),
(4,'KOMA'),
(4,'KORO'),
(4,'KORU'),
(4,'KOTA'),
(4,'KOYU'),
(4,'KOZA'),
(4,'KOŞU'),
(4,'KRAL'),
(4,'KREP'),
(4,'KREŞ'),
(4,'KROM'),
(4,'KROS'),
(4,'KRİZ'),
(4,'KULE'),
(4,'KULP'),
(4,'KUPA'),
(4,'KURA'),
(4,'KURS'),
(4,'KURT'),
(4,'KUTU'),
(4,'KUZU'),
(4,'KÖLE'),
(4,'KÖRE'),
(4,'KÖSE'),
(4,'KÖTÜ'),
(4,'KÖŞE'),
(4,'KÜFE'),
(4,'KÜME'),
(4,'KÜPE'),
(4,'KÜRE'),
(4,'KÜRK'),
(4,'KİLO'),
(4,'KİST'),
(4,'KİVİ'),
(4,'LAPA'),
(4,'LAVA'),
(4,'LEKE'),
(4,'LENF'),
(4,'LENS'),
(4,'LOBİ'),
(4,'LOCA'),
(4,'LOGO'),
(4,'LORT'),
(4,'LÜKS'),
(4,'LÜLE'),
(4,'LİFT'),
(4,'LİGA'),
(4,'LİNK'),
(4,'LİNÇ'),
(4,'LİSE'),
(4,'MAAŞ'),
(4,'MAMA'),
(4,'MARJ'),
(4,'MARK'),
(4,'MARS'),
(4,'MART'),
(4,'MARŞ'),
(4,'MASK'),
(4,'MAVİ'),
(4,'MAYO'),
(4,'MAŞA'),
(4,'MEAL'),
(4,'MEGA'),
(4,'MEME'),
(4,'MENÜ'),
(4,'MEST'),
(4,'META'),
(4,'MEZE'),
(4,'MEŞE'),
(4,'MONT'),
(4,'MORG'),
(4,'MORS'),
(4,'MUAF'),
(4,'MÜLK'),
(4,'MÜZE'),
(4,'MİNİ'),
(4,'NARA'),
(4,'NAİF'),
(4,'NENE'),
(4,'NEON'),
(4,'NEŞE'),
(4,'NOEL'),
(4,'NORM'),
(4,'NÖTR'),
(4,'NÜVE'),
(4,'NİCE'),
(4,'NİDA'),
(4,'NİNE'),
(4,'NİYE'),
(4,'OBEZ'),
(4,'OBJE'),
(4,'OBUA'),
(4,'OBUR'),
(4,'OBÜS'),
(4,'OCAK'),
(4,'ODUN'),
(4,'OFİS'),
(4,'OKEY'),
(4,'OKKA'),
(4,'OKUR'),
(4,'OLDU'),
(4,'OLGU'),
(4,'OLTA'),
(4,'OLUK'),
(4,'OLUR'),
(4,'OLUŞ'),
(4,'OMUZ'),
(4,'ONAY'),
(4,'ONUR'),
(4,'OPAK'),
(4,'OPAL'),
(4,'ORAK'),
(4,'ORAN'),
(4,'ORDU'),
(4,'ORTA'),
(4,'ORUÇ'),
(4,'OTEL'),
(4,'OTUZ'),
(4,'OVAL'),
(4,'OYSA'),
(4,'OYUK'),
(4,'OYUN'),
(4,'OZAN'),
(4,'OZON'),
(4,'PAHA'),
(4,'PALA'),
(4,'PAPA'),
(4,'PARS'),
(4,'PASO'),
(4,'PAÇA'),
(4,'PEKİ'),
(4,'PERT'),
(4,'PERİ'),
(4,'PEST'),
(4,'PLAJ'),
(4,'PLAK'),
(4,'PLAN'),
(4,'POLO'),
(4,'POSA'),
(4,'POST'),
(4,'POTA'),
(4,'PRES'),
(4,'PRİM'),
(4,'PRİZ'),
(4,'PUAN'),
(4,'PUMA'),
(4,'PURO'),
(4,'PUSU'),
(4,'PÜRE'),
(4,'PİKE'),
(4,'PİPO'),
(4,'PİRE'),
(4,'PİST'),
(4,'SÜRÜ'),
(4,'SORU'),
(4,'ÖLÜM'),
(4,'UFAK'),
(4,'İÇKİ'),
(4,'ÖYLE'),
(4,'ÖNCE'),
(4,'YANİ'),
(4,'GERİ'),
(4,'YİNE'),
(4,'UZUN'),
(4,'ÖZEL'),
(4,'GENÇ'),
(4,'SÜRE'),
(4,'YEDİ'),
(5,'ACABA'),
(5,'ACEMİ'),
(5,'AHKAM'),
(5,'ALAKA'),
(5,'ALÇAK'),
(5,'AMELE'),
(5,'ANLIK'),
(5,'APTAL'),
(5,'ARTIK'),
(5,'BAKAN'),
(5,'BAKLA'),
(5,'BALIK'),
(5,'BARON'),
(5,'BATIK'),
(5,'BEKAR'),
(5,'BEŞER'),
(5,'BELLİ'),
(5,'BENCE'),
(5,'BOYUT'),
(5,'BUGÜN'),
(5,'CESUR'),
(5,'CİDDİ'),
(5,'ÇABUK'),
(5,'ÇAKMA'),
(5,'ÇELLO'),
(5,'ÇIKAR'),
(5,'ÇOCUK'),
(5,'ÇÜNKÜ'),
(5,'DALGA'),
(5,'DEMEK'),
(5,'DERGİ'),
(5,'DEVAM'),
(5,'DİĞER'),
(5,'DOLAR'),
(5,'DÜNYA'),
(5,'DÜŞÜN'),
(5,'ERKEK'),
(5,'ETMEK'),
(5,'EVLAT'),
(5,'EVREN'),
(5,'FAZLA'),
(5,'GİZLİ'),
(5,'GÜZEL'),
(5,'HAKLI'),
(5,'HALKA'),
(5,'HAMAM'),
(5,'HAPİS'),
(5,'HAYDİ'),
(5,'HAYAT'),
(5,'HEPSİ'),
(5,'HESAP'),
(5,'HUZUR'),
(5,'ISLIK'),
(5,'İPUCU'),
(5,'İSTER'),
(5,'KABUL'),
(5,'KADRO'),
(5,'KAFES'),
(5,'KALEM'),
(5,'KALÇA'),
(5,'KANIT'),
(5,'KAPAN'),
(5,'KAPUT'),
(5,'KARLI'),
(5,'KARŞI'),
(5,'KASIM'),
(5,'KASİS'),
(5,'KATİL'),
(5,'KAVGA'),
(5,'KAVİM'),
(5,'KAYIK'),
(5,'KAZMA'),
(5,'KEMİK'),
(5,'KENET'),
(5,'KEPÇE'),
(5,'KESER'),
(5,'KESİM'),
(5,'KETEN'),
(5,'KİMSE'),
(5,'KIRMA'),
(5,'KIVAM'),
(5,'KIYAK'),
(5,'KİLER'),
(5,'KİTLE'),
(5,'KOLAJ'),
(5,'KOMİK'),
(5,'KOPUK'),
(5,'KORNA'),
(5,'KOVAN'),
(5,'KURGU'),
(5,'KURUL'),
(5,'KÜMES'),
(5,'KÜTÜK'),
(5,'LAKAP'),
(5,'LANET'),
(5,'LAZIM'),
(5,'LOKMA'),
(5,'MANTO'),
(5,'MANAV'),
(5,'MANDA'),
(5,'MAYIS'),
(5,'MİMAR'),
(5,'MÜDÜR'),
(5,'NEFES'),
(5,'NELER'),
(5,'OLGUN'),
(5,'OLMAK'),
(5,'OLMAZ'),
(5,'ONLUK'),
(5,'ORMAN'),
(5,'ÖNDER'),
(5,'ÖNLEM'),
(5,'PARTİ'),
(5,'SAHNE'),
(5,'SAVAŞ'),
(5,'SAYFA'),
(5,'SAYIN'),
(5,'ŞİMDİ'),
(5,'ŞÖYLE'),
(5,'TAMAM'),
(5,'TANRI'),
(5,'TUHAF'),
(5,'UYGUN'),
(5,'YAPMA'),
(5,'YAŞLI'),
(5,'BÖYLE'),
(5,'NEDEN'),
(5,'NASIL'),
(5,'ARABA'),
(5,'ACELE'),
(5,'DOĞUM'),
(6,'BAHŞİŞ'),
(6,'BALKON'),
(6,'BASKIN'),
(6,'BAŞKAN'),
(6,'BAYGIN'),
(6,'BAYRAK'),
(6,'BURADA'),
(6,'BURASI'),
(6,'CUMHUR'),
(6,'DAKİKA'),
(6,'DOKTOR'),
(6,'DÜRÜST'),
(6,'DÜRBÜN'),
(6,'ENERJİ'),
(6,'GEZMEK'),
(6,'GÖZLÜK'),
(6,'HAFIZA'),
(6,'HARİKA'),
(6,'HARİTA'),
(6,'HERKES'),
(6,'HİKAYE'),
(6,'HİZMET'),
(6,'İKİNCİ'),
(6,'İLETİM'),
(6,'İLGİLİ'),
(6,'KAMERA'),
(6,'KAPLAN'),
(6,'KAPTAN'),
(6,'KAVRAM'),
(6,'KAZMAK'),
(6,'KELİME'),
(6,'KİMLİK'),
(6,'KİRPİK'),
(6,'KOLTUK'),
(6,'KOMPLE'),
(6,'KORKAK'),
(6,'KURBAN'),
(6,'KURŞUN'),
(6,'KÜLTÜR'),
(6,'LÜTFEN'),
(6,'MAĞAZA'),
(6,'MAKİNE'),
(6,'MANTIK'),
(6,'MEMNUN'),
(6,'MERCEK'),
(6,'MERKEZ'),
(6,'MERMER'),
(6,'MESLEK'),
(6,'MİKTAR'),
(6,'MİLLET'),
(6,'MÜMKÜN'),
(6,'NEREYE'),
(6,'NUMARA'),
(6,'OYUNCU'),
(6,'PARDON'),
(6,'PİYANO'),
(6,'PLATİN'),
(6,'RENKLİ'),
(6,'SANİYE'),
(6,'SEÇMEK'),
(6,'SESSİZ'),
(6,'SİSTEM'),
(6,'SÜRÜCÜ'),
(6,'TABURE'),
(6,'TAHMİN'),
(6,'TEKLİF'),
(6,'TEKRAR'),
(6,'TERCİH'),
(6,'TOPLUM'),
(6,'UNUTMA'),
(6,'VARLIK'),
(6,'VERMEK'),
(6,'YALNIZ'),
(6,'YARDIM'),
(6,'YÜKSEK'),
(6,'YÜZMEK'),
(6,'ZENGİN'),
(6,'ZORLUK'),
(6,'ÇARPMA'),
(6,'ÇEVİRİ'),
(6,'ÜRETİM')
) as v(length,word)
on conflict (answer_version,length,word) do update set enabled=true;

create or replace function public.pick_fresh_multiplayer_answer(
  p_length integer,
  p_player_ids uuid[],
  p_exclude text default null
)
returns text
language plpgsql
security definer
volatile
set search_path = public, extensions, pg_temp
as $$
declare
  chosen text;
begin
  if p_length not in (4,5,6) then raise exception 'Geçersiz harf sayısı'; end if;

  select aw.word into chosen
  from public.multiplayer_answer_words aw
  where aw.answer_version='A2'
    and aw.length=p_length
    and aw.enabled=true
    and (p_exclude is null or aw.word<>p_exclude)
    and not exists(
      select 1
      from (
        select history.answer_word
        from (
          select b.ended_at, bs.answer_word
          from public.bot_matches b
          join public.bot_match_secrets bs on bs.match_id=b.id
          where b.status='ended'
            and b.word_length=p_length
            and b.player_id=any(p_player_ids)
          union all
          select l.ended_at, ls.answer_word
          from public.live_matches l
          join public.live_match_secrets ls on ls.match_id=l.id
          where l.status='ended'
            and l.word_length=p_length
            and (l.host_id=any(p_player_ids) or l.guest_id=any(p_player_ids))
        ) history
        order by history.ended_at desc nulls last
        limit 24
      ) recent
      where recent.answer_word=aw.word
    )
  order by random()
  limit 1;

  if chosen is null then
    select aw.word into chosen
    from public.multiplayer_answer_words aw
    where aw.answer_version='A2'
      and aw.length=p_length
      and aw.enabled=true
      and (p_exclude is null or aw.word<>p_exclude)
    order by random()
    limit 1;
  end if;

  if chosen is null then
    select aw.word into chosen
    from public.multiplayer_answer_words aw
    where aw.answer_version='A1'
      and aw.length=p_length
      and aw.enabled=true
      and (p_exclude is null or aw.word<>p_exclude)
    order by random()
    limit 1;
  end if;

  if chosen is null then raise exception 'Online cevap havuzu yüklenmemiş'; end if;
  return chosen;
end;
$$;

-- Mevcut online maç fonksiyonlarını yeniden tanımlamak yerine secret insertlerini
-- A2 + tekrar korumasına yönlendir. Böylece önceki fairness / reconnect / bot
-- davranışları aynen korunur.
create or replace function public.enforce_fresh_live_answer_a2()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  m public.live_matches%rowtype;
  previous_answer text := null;
  players uuid[];
begin
  select * into m from public.live_matches where id=new.match_id;
  if not found then raise exception 'Canlı maç bulunamadı'; end if;

  if m.parent_match_id is not null then
    select s.answer_word into previous_answer
    from public.live_match_secrets s
    where s.match_id=m.parent_match_id;
  end if;

  players:=array_remove(array[m.host_id,m.guest_id]::uuid[],null);
  new.answer_word:=public.pick_fresh_multiplayer_answer(m.word_length,players,previous_answer);
  new.answer_version:='A2';
  return new;
end;
$$;

create or replace function public.enforce_fresh_bot_answer_a2()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  m public.bot_matches%rowtype;
begin
  select * into m from public.bot_matches where id=new.match_id;
  if not found then raise exception 'Bot maçı bulunamadı'; end if;

  new.answer_word:=public.pick_fresh_multiplayer_answer(m.word_length,array[m.player_id]::uuid[],null);
  new.answer_version:='A2';
  return new;
end;
$$;

drop trigger if exists trg_live_secret_fresh_a2 on public.live_match_secrets;
create trigger trg_live_secret_fresh_a2
before insert on public.live_match_secrets
for each row execute function public.enforce_fresh_live_answer_a2();

drop trigger if exists trg_bot_secret_fresh_a2 on public.bot_match_secrets;
create trigger trg_bot_secret_fresh_a2
before insert on public.bot_match_secrets
for each row execute function public.enforce_fresh_bot_answer_a2();

revoke all on function public.pick_fresh_multiplayer_answer(integer,uuid[],text) from public, anon, authenticated;
revoke all on function public.enforce_fresh_live_answer_a2() from public, anon, authenticated;
revoke all on function public.enforce_fresh_bot_answer_a2() from public, anon, authenticated;
